name: Auto update

on:
  push:
    branches:
      - master
    paths:
      - 'user-rule.txt'
  schedule:
    - cron: '33 19 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Install packages
        run: |
          sudo apt-get install openssh-client python3-setuptools

      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.TOKEN }}

      - uses: actions/checkout@v3
        with:
          repository: JinnLynn/genpac
          path: genpac
          # ref: '1223b93d6a3c24830e493325d64505911d1bc8bd'

      - uses: actions/checkout@v3
        with:
          repository: gfwlist/gfwlist
          path: gfwlist

      # - uses: petronny/git-config-user@master
      #   with:
      #     path: .

      - run: |
          echo $PATH
          cd genpac
          sudo pip3 install --no-cache-dir --target=/home/runner/.local/bin/genpac genpac .
          export PATH=$PATH:~/.python/current/bin

      - name: Update
        run: |
          set -x

          genpac --pac-proxy "SOCKS5 127.0.0.1:1080; SOCKS 127.0.0.1:1080; DIRECT;" --gfwlist-url - --gfwlist-local gfwlist/gfwlist.txt --user-rule-from user-rule.txt -o gfwlist.pac
          sed '1,7d' -i gfwlist.pac

          # git add gfwlist.pac
          # git commit -m "[$(LANG=C date)] auto update" || exit 0

          # [ -n "${{ secrets.READ_ONLY }}" ] && git show && exit 0

          # git push origin master

      - name: Push
        run: |
          sed -i "1i\\/\/ Last Modified: $(LANG=C date)\n" gfwlist.pac
          git config --global user.name 'wolfsilver'
          git config --global user.email 'wolfsilver@users.noreply.github.com'
          git add gfwlist.pac
          git commit -m "[$(LANG=C date)] auto update" || exit 0
          git push origin master
